apiVersion: v1
kind: Pod
metadata: 
  name: [[forms[0].name]]
[[ forms[0].namespace ? "  namespace: " + forms[0].namespace + "\n" : ""]]
spec: 
  conatiners:
    - image: [[forms[0].image]]
      name: [[forms[0].name]]
      resources: {}